### ISSUE TITLE
Publish .deb file

### ISSUE THREAD

**Issue by piranna** [iocroblab/coindesigner#1]
I'm working for a research project at Rey Juan Carlos University and I was going to create .deb archive to distribute an old binary of CoinDesigner that we have laying here, when I got to knew about your updated fork :-) Do you have binary .deb files published somewhere, specially for Ubuntu 16.04? Is your fork ready for such recent library versions?

**Comment by lepalom** [comment]
We have it for Debian Jessie and Ubuntu 14.04

http://sir.upc.edu/debian-robotics/pool/main/c/coindesigner/

I can update it for 16.04 but let me some days.

**Comment by piranna** [comment]
> I can update it for 16.04 but let me some days.

Ok, that would be cool :-) Both 16.04 or 16.10 would be fine for me,
thanks! :-D
